# Generated by Django 5.2.14 on 2026-05-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsetCigem',
            fields=[
                ('id_aset', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_aset', models.CharField(choices=[('Alat', 'Alat'), ('Bahan', 'Bahan'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('nama_aset', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'aset_cigem',
            },
        ),
        migrations.CreateModel(
            name='GayaKonten',
            fields=[
                ('id_gaya', models.AutoField(primary_key=True, serialize=False)),
                ('nama_gaya', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gaya_konten',
            },
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id_kriteria', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_kriteria', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'kriteria',
            },
        ),
        migrations.CreateModel(
            name='PlatformMedsos',
            fields=[
                ('id_platform', models.AutoField(primary_key=True, serialize=False)),
                ('nama_platform', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'platform_medsos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('nama_lengkap', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='NilaiGayaKonten',
            fields=[
                ('id_nilai_gaya', models.AutoField(primary_key=True, serialize=False)),
                ('skor_aktual', models.IntegerField()),
                ('id_gaya', models.ForeignKey(db_column='id_gaya', on_delete=django.db.models.deletion.CASCADE, to='spk_app.gayakonten')),
                ('id_kriteria', models.ForeignKey(db_column='id_kriteria', on_delete=django.db.models.deletion.CASCADE, to='spk_app.kriteria')),
            ],
            options={
                'db_table': 'nilai_gaya_konten',
            },
        ),
        migrations.CreateModel(
            name='RiwayatSpk',
            fields=[
                ('id_riwayat', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('kategori_input', models.CharField(max_length=100)),
                ('nama_platform', models.CharField(max_length=100)),
                ('teks_ide_konten', models.TextField()),
                ('skor_akhir_spk', models.FloatField()),
                ('id_platform', models.ForeignKey(db_column='id_platform', on_delete=django.db.models.deletion.CASCADE, related_name='platform_asal', to='spk_app.platformmedsos')),
                ('id_platform_rekomendasi', models.ForeignKey(db_column='id_platform_rekomendasi', on_delete=django.db.models.deletion.CASCADE, related_name='rekomendasi', to='spk_app.platformmedsos')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='spk_app.user')),
            ],
            options={
                'db_table': 'riwayat_spk',
            },
        ),
        migrations.CreateModel(
            name='EvaluasiKonten',
            fields=[
                ('id_evaluasi', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_tayangan', models.IntegerField()),
                ('status_konten', models.CharField(choices=[('Sukses', 'Sukses'), ('Gagal', 'Gagal'), ('Pending', 'Pending')], max_length=50)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('id_riwayat', models.OneToOneField(db_column='id_riwayat', on_delete=django.db.models.deletion.CASCADE, to='spk_app.riwayatspk')),
            ],
            options={
                'db_table': 'evaluasi_konten',
            },
        ),
        migrations.CreateModel(
            name='DetailRiwayatAset',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('id_aset', models.ForeignKey(db_column='id_aset', on_delete=django.db.models.deletion.CASCADE, to='spk_app.asetcigem')),
                ('id_riwayat', models.ForeignKey(db_column='id_riwayat', on_delete=django.db.models.deletion.CASCADE, to='spk_app.riwayatspk')),
            ],
            options={
                'db_table': 'detail_riwayat_aset',
            },
        ),
        migrations.CreateModel(
            name='TargetPlatform',
            fields=[
                ('id_target', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_target', models.IntegerField()),
                ('jenis_faktor', models.CharField(choices=[('Core', 'Core'), ('Secondary', 'Secondary')], max_length=50)),
                ('id_kriteria', models.ForeignKey(db_column='id_kriteria', on_delete=django.db.models.deletion.CASCADE, to='spk_app.kriteria')),
                ('id_platform', models.ForeignKey(db_column='id_platform', on_delete=django.db.models.deletion.CASCADE, to='spk_app.platformmedsos')),
            ],
            options={
                'db_table': 'target_platform',
            },
        ),
    ]
